[settings]
# paranoid = true
env_file = ".env"
experimental = true
idiomatic_version_file_enable_tools = ["node"]
npm.bun = true
node.compile = false
node.gpg_verify = true
pipx.uvx = true
python.uv_venv_auto = true
python.uv_venv_create_args = ["--seed"]
terminal_progress = false


[tools]
bun = "latest"
cargo-binstall = "latest"
deno = "latest"
go = "latest"
lua = "5.1"
node = { version = "25", postinstall = "mise run npm-install-global-packages" }
python = { version = "3.13", postinstall = "mise run python-install-global-packages" }
ruby = { version = "latest", postinstall = "mise run ruby-install-global-packages" }
rust = "nightly"
uv = "latest"

# Order matters, these should be installed after the tools above, otherwise $PATH may be clobbered
aws-cli = "latest"
vault = "latest"
delta = "latest"
stylua = "latest"
prettier = "latest"
tree-sitter = "latest"

"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:mcp-hub" = "latest"
"npm:@github/copilot" = "latest"
"npm:markdownlint-cli2" = "latest"

"pipx:vectorcode[lsp,mcp]" = "latest"


[tasks.global-install-packages-npm]
description = "Install global NPM packages"
alias = "gin"
run = ["npm install -g npm@latest", "npm install -g neovim@latest"]

[tasks.global-install-packages-python]
description = "Install global Python packages"
alias = "gip"
run = ["uv tool install --upgrade pynvim"]

[tasks.global-install-packages-ruby]
description = "Install global Ruby gems"
alias = "gir"
run = ["gem install neovim"]

[tasks.install-global-packages]
description = "Install all global packages"
alias = "gi"
run = [
  { task = "global-install-packages-npm" },
  { task = "global-install-packages-python" },
  { task = "global-install-packages-ruby" },
]
